#!/usr/bin/env python3
# coding=utf-8

'''cvlc_simple_alarm

Run `python -i /path/to/cvlc_simple_alarm`, then start timer in interactive
interpreter with `t.run()`.
'''

import os
import sys
from subprocess import Popen, DEVNULL, STDOUT
from timeman import Timer

def cvlc_alarm():
    cmd = ('cvlc', '--no-metadata-network-access', '--repeat', alarmfp)
    alarm_procs.append(Popen(cmd, stdout=DEVNULL, stderr=STDOUT))
    alarm_procs[-1].wait()

def kill_alarms():
    for proc in alarm_procs:
        try:
            proc.kill()
        except ProcessLookupError:
            pass
    alarm_procs.clear()

def rebuild_timers():
    for i in (t, b):
        i.cancel()
    build_timers()

def build_timers():
    global t, b
    t = Timer(1500, cvlc_alarm)
    b = Timer(300, cvlc_alarm)

alarmfvar = 'SYSPOL_SOUND_ALARM_INFO_FP'

try:
    alarmfp = os.environ[alarmfvar]
    if not os.access(alarmfp, os.R_OK):
        raise PermissionError
except KeyError:
    print('Environment variable `{}` nonexistent'.format(alarmfvar),
            file=sys.stderr)
    raise
except PermissionError:
    print("Can't read file `{}`".format(alarmfp), file=sys.stderr)
    raise

alarm_procs = []
build_timers()
