#!/usr/bin/env python3
# coding=utf-8

'''get-category-names'''

import sys

SEP = '/'
categories = (l.strip() for l in sys.stdin.readlines())
category_names = (cname for c in categories for cname in c.split(SEP))
print(*category_names, sep='\n')

# vim: ft=python
