#!/usr/bin/env python3
# coding=utf-8

'''ls-cat'''

import json
from os import environ, linesep
from os.path import join

from timeman import get_categories

DEFAULT_PROFILE_NAME = 'default'
PROFILE_EXT = 'json'
DEFAULT_PROFILE_FNAME = '.'.join((DEFAULT_PROFILE_NAME, PROFILE_EXT))

config_dir = environ['TIMEMAN']
DEFAULT_PROFILE_PATH = join(config_dir, DEFAULT_PROFILE_FNAME)

with open(DEFAULT_PROFILE_PATH) as f:
    prf_default = json.load(f)

taskcoach_cfg_dirs = prf_default['taskcoach_cfg_dirs']
atimetracker_cfg_dirs = prf_default['atimetracker_cfg_dirs']

categories = list(sorted(set(
    get_categories(taskcoach_cfg_dirs, atimetracker_cfg_dirs))))

print(*categories, sep='\n')

# vim: ft=python
