#!/usr/bin/env python3
# coding=utf-8

'''ls-cat'''

from timeman import get_categories
from timeman.config import get_default_profile
from timeman.constants import *

prf_default = get_default_profile()
taskcoach_cfg_dirs = prf_default[PROFILE_TASKCOACH_CONFIG_DIRS_KEY]
atimetracker_cfg_dirs = prf_default[PROFILE_ATIMETRACKER_CONFIG_DIRS_KEY]

categories = sorted(set(
    get_categories(taskcoach_cfg_dirs, atimetracker_cfg_dirs)))

print(*categories, sep='\n')

# vim: ft=python
