#!/usr/bin/env python3
# coding=utf-8

'''tsk-cateft-rpt
'''

import sys
import json
from os import environ
from os.path import pathsep
from datetime import datetime, timedelta
from argparse import ArgumentParser
from collections import OrderedDict

from timeman import (validate, get_category_efforts, plot_category_efforts,
        DEFAULT_DATETIME_FMT, get_category_efforts_details, EFFORT_KEYS_SORTED)

stderro_fmt = '{}: {}'
stderro_names = ('start', 'end', 'total_effort_time', 'total_time',
        'effort_fraction')
stderro_vals = []

parser = ArgumentParser()
parser.add_argument('category_subjects', nargs='*',
        help='''For every category x, this selects all tasks of category x including those of any subcategory of x. This does not select tasks of a bare category x excluding those of subcategories of x. For example, selecting `health`, `health/meta`, `health/misc` will contain redundant data because `health` matches _any_ tasks of category `health` _including_ those of (sub)category `health/misc` and `health/meta`.''')
parser.add_argument('-s', '--start')
parser.add_argument('-e', '--end')
parser.add_argument('-t', '--taskcoach-config-dirs', nargs='*', required=True)
parser.add_argument('-a', '--atimetracker-config-dirs', nargs='*',
        required=True)
parser.add_argument('-p', '--img-out', nargs='*')
parser.add_argument('-r', '--reverse', action='store_true')
parser.add_argument('-V', '--validate', action='store_true')
parser.add_argument('-d', '--dump-path')
args = parser.parse_args()

TASKCOACH_FP = (args.taskcoach_config_dirs if args.taskcoach_config_dirs
        else environ['SYSPOL_TASKCOACH_FP'].split(pathsep))
CATEGORIES = (args.category_subjects if args.category_subjects
    else environ['SYSPOL_TASKCOACH_CATEGORY_EFFORT_VIEWER_DEFAULT_CATEGORIES']\
            .split())
START = datetime.strptime(args.start if args.start
    else environ['SYSPOL_TASKCOACH_CATEGORY_EFFORT_VIEWER_DEFAULT_START'],
    DEFAULT_DATETIME_FMT)
stderro_vals.append(START)
try:
    END = datetime.strptime(args.end if args.end
        else environ['SYSPOL_TASKCOACH_CATEGORY_EFFORT_VIEWER_DEFAULT_END'],
        DEFAULT_DATETIME_FMT)
except (KeyError, ValueError):
    END = datetime.now()
stderro_vals.append(END)

IMG_PLOT_FP = args.img_out if args.img_out else ()

# config done

def dump():
    def order_keys(efft):
        x = OrderedDict()
        for key in EFFORT_KEYS_SORTED:
            x[key] = efft[key]
        return x

    efforts = get_category_efforts_details(CATEGORIES, START, END, TASKCOACH_FP,
            args.atimetracker_config_dirs)
    efforts.sort(key=lambda eft: eft['start'])
    for eft in efforts:
        eft['effort'] = str(eft['end'] - eft['start'])
        eft['start'] = str(eft['start'])
        eft['end'] = str(eft['end'])
    efforts = tuple(map(order_keys, efforts))
    sort_keys = False
    with open(args.dump_path, 'w') as f:
        json.dump(efforts, f, sort_keys=sort_keys, indent=2)

if args.validate:
    assert validate(TASKCOACH_FP, args.atimetracker_config_dirs)

if args.dump_path:
    dump()
    sys.exit(0)

out = tuple((category, effort) for category, effort in
        get_category_efforts(CATEGORIES, START, END, TASKCOACH_FP,
            args.atimetracker_config_dirs))
total_effort = sum(record[1] for record in out)
stderro_vals.append(timedelta(seconds=total_effort))
if total_effort:
    out = [(category, effort, effort / total_effort)
            for category, effort in out]
else:
    default_ratio = float()
    out = [(category, effort, default_ratio)
            for category, effort in out]

out.sort(key=lambda record: record[1], reverse=args.reverse)
total_time = (END - START).total_seconds()
stderro_vals.append(timedelta(seconds=total_time))
stderro_vals.append(total_effort / total_time)

for record in out:
    print('\t'.join(str(i) for i in record))

print(file=sys.stderr)
for i, stderro_val in enumerate(stderro_vals):
    print(stderro_fmt.format(stderro_names[i], stderro_val), file=sys.stderr)

plot_category_efforts(out, IMG_PLOT_FP)

# vim: ft=python
